import { isStateName } from '../lib/data/landTransferTaxRates';

export interface PlzTable {
  /** PLZ (5 Ziffern) -> Bundesland, nur eindeutige PLZ. */
  unique: Map<string, string>;
  /** PLZ (5 Ziffern) -> alle Bundesländer, alphabetisch; nur PLZ in mehr als einem Land. */
  ambiguous: Map<string, string[]>;
}

const EXPECTED_HEADER = 'Ort;Plz;Bundesland';

/** Bekannte Tippfehler in der Quelldatei. */
const STATE_TYPOS: Record<string, string> = {
  'Schlewig-Holstein': 'Schleswig-Holstein',
};

export function parsePostcodeCsv(csv: string): PlzTable {
  const lines = csv.replace(/^﻿/, '').split(/\r?\n/);
  const header = lines.shift() ?? '';
  if (header.trim() !== EXPECTED_HEADER) {
    throw new Error(`Unexpected CSV header: "${header}" (expected "${EXPECTED_HEADER}")`);
  }

  const statesByPlz = new Map<string, Set<string>>();
  for (const line of lines) {
    if (!line.trim()) continue;
    const [, rawPlz = '', rawState = ''] = line.split(';');
    const plzText = rawPlz.trim();
    const stateText = rawState.trim();
    if (!plzText && !stateText) continue; // ";;" rows in the source file

    if (!/^\d{1,5}$/.test(plzText)) throw new Error(`Invalid PLZ in line: ${line}`);
    const plz = plzText.padStart(5, '0');
    const state = STATE_TYPOS[stateText] ?? stateText;
    if (!isStateName(state)) throw new Error(`Unknown Bundesland "${state}" in line: ${line}`);

    const set = statesByPlz.get(plz) ?? new Set<string>();
    set.add(state);
    statesByPlz.set(plz, set);
  }

  const unique = new Map<string, string>();
  const ambiguous = new Map<string, string[]>();
  for (const [plz, states] of statesByPlz) {
    if (states.size === 1) unique.set(plz, [...states][0]);
    else ambiguous.set(plz, [...states].sort((a, b) => a.localeCompare(b, 'de')));
  }
  return { unique, ambiguous };
}

/** Fasst aufeinanderfolgende PLZ desselben Landes zu [von, bis]-Bereichen zusammen. */
function toRanges(plzs: number[]): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];
  for (const plz of plzs) {
    const last = ranges[ranges.length - 1];
    if (last && plz === last[1] + 1) last[1] = plz;
    else ranges.push([plz, plz]);
  }
  return ranges;
}

export function renderTableModule(table: PlzTable, sourceNote: string): string {
  const numbersByState = new Map<string, number[]>();
  for (const [plz, state] of table.unique) {
    const list = numbersByState.get(state) ?? [];
    list.push(Number(plz));
    numbersByState.set(state, list);
  }

  const stateLines = [...numbersByState.keys()]
    .sort((a, b) => a.localeCompare(b, 'de'))
    .map((state) => {
      const sorted = numbersByState.get(state)!.sort((a, b) => a - b);
      return `  ${JSON.stringify(state)}: ${JSON.stringify(toRanges(sorted))},`;
    });

  const ambiguousLines = [...table.ambiguous.keys()]
    .sort()
    .map((plz) => `  ${JSON.stringify(plz)}: ${JSON.stringify(table.ambiguous.get(plz))},`);

  return [
    '/* eslint-disable */',
    '// GENERATED by scripts/generatePlzTable.ts — do not edit by hand.',
    `// Quelle: ${sourceNote}`,
    '',
    '/** Bundesland -> Bereiche [von, bis] aufeinanderfolgender, eindeutig zugeordneter PLZ. */',
    'export const PLZ_RANGES: Record<string, ReadonlyArray<readonly [number, number]>> = {',
    ...stateLines,
    '};',
    '',
    '/** PLZ, die in mehr als einem Bundesland liegen (alphabetisch). */',
    'export const AMBIGUOUS_PLZ: Record<string, readonly string[]> = {',
    ...ambiguousLines,
    '};',
    '',
  ].join('\n');
}
