import { isStateName } from '../lib/data/landTransferTaxRates';

export interface PlzTable {
  /** PLZ (5 Ziffern) -> Bundesland, nur eindeutige PLZ. */
  unique: Map<string, string>;
  /** PLZ (5 Ziffern) -> alle Bundesländer, alphabetisch; nur PLZ in mehr als einem Land. */
  ambiguous: Map<string, string[]>;
}

const EXPECTED_HEADER = 'Ort;Plz;Bundesland';
const RANGES_PER_LINE = 8;

/** Locale-unabhängiger Vergleich (UTF-16-Code-Units), damit die Ausgabe deterministisch ist. */
const compareText = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

/** Bekannte Tippfehler in der Quelldatei. */
const STATE_TYPOS: Record<string, string> = {
  'Schlewig-Holstein': 'Schleswig-Holstein',
};

export function parsePostcodeCsv(csv: string): PlzTable {
  const lines = csv.replace(/^\uFEFF/, '').split(/\r?\n/);
  const [header = '', ...rows] = lines;
  if (header.trim() !== EXPECTED_HEADER) {
    throw new Error(`Unexpected CSV header: "${header}" (expected "${EXPECTED_HEADER}")`);
  }

  const statesByPlz = new Map<string, Set<string>>();
  for (const line of rows) {
    if (!line.trim()) continue;
    const columns = line.split(';');
    if (columns.every((column) => !column.trim())) continue; // ";;" rows in the source file
    if (columns.length !== 3) throw new Error(`Malformed row: ${line}`);
    const plzText = columns[1].trim();
    const stateText = columns[2].trim();

    if (!/^\d{1,5}$/.test(plzText)) throw new Error(`Invalid PLZ in line: ${line}`);
    const plz = plzText.padStart(5, '0');
    const state = STATE_TYPOS[stateText] ?? stateText;
    if (!isStateName(state)) throw new Error(`Unknown Bundesland "${state}" in line: ${line}`);

    const set = statesByPlz.get(plz) ?? new Set<string>();
    set.add(state);
    statesByPlz.set(plz, set);
  }

  if (statesByPlz.size === 0) throw new Error('CSV contains no data rows');

  const unique = new Map<string, string>();
  const ambiguous = new Map<string, string[]>();
  for (const [plz, states] of statesByPlz) {
    if (states.size === 1) unique.set(plz, [...states][0]);
    else ambiguous.set(plz, [...states].sort(compareText));
  }
  return { unique, ambiguous };
}

/** Fasst aufeinanderfolgende PLZ desselben Landes zu [von, bis]-Bereichen zusammen. */
function toRanges(plzs: number[]): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];
  for (const plz of plzs) {
    const last = ranges[ranges.length - 1];
    if (last && plz === last[1] + 1) last[1] = plz;
    else ranges.push([plz, plz]);
  }
  return ranges;
}

export function renderTableModule(table: PlzTable, sourceNote: string): string {
  const numbersByState = new Map<string, number[]>();
  for (const [plz, state] of table.unique) {
    const list = numbersByState.get(state) ?? [];
    list.push(Number(plz));
    numbersByState.set(state, list);
  }

  const stateLines = [...numbersByState.entries()]
    .sort(([a], [b]) => compareText(a, b))
    .flatMap(([state, numbers]) => {
      const ranges = toRanges(numbers.sort((a, b) => a - b)).map((range) => JSON.stringify(range));
      const chunks: string[] = [];
      for (let i = 0; i < ranges.length; i += RANGES_PER_LINE) {
        chunks.push(ranges.slice(i, i + RANGES_PER_LINE).join(','));
      }
      const body = chunks.map((chunk, i) => `    ${chunk}${i < chunks.length - 1 ? ',' : ''}`);
      return [`  ${JSON.stringify(state)}: [`, ...body, '  ],'];
    });

  const ambiguousLines = [...table.ambiguous.entries()]
    .sort(([a], [b]) => compareText(a, b))
    .map(([plz, states]) => `  ${JSON.stringify(plz)}: ${JSON.stringify(states)},`);

  return [
    '// GENERATED by scripts/generatePlzTable.ts — do not edit by hand.',
    `// Quelle: ${sourceNote}`,
    '',
    '/** Bundesland -> Bereiche [von, bis] aufeinanderfolgender, eindeutig zugeordneter PLZ. */',
    'export const PLZ_RANGES: Record<string, ReadonlyArray<readonly [number, number]>> = {',
    ...stateLines,
    '};',
    '',
    '/** PLZ, die in mehr als einem Bundesland liegen (alphabetisch). */',
    'export const AMBIGUOUS_PLZ: Record<string, readonly string[]> = {',
    ...ambiguousLines,
    '};',
    '',
  ].join('\n');
}
